//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 10:27:01 AM PST 
//


package com.nike.mptaxmanager.model.onesource.response;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class ConvertedCurrencyAmountType {

    @XmlElement(name = "DOCUMENT_AMOUNT")
    protected String documentamount;
    @XmlElement(name = "UNROUNDED_DOCUMENT_AMOUNT")
    protected String unroundeddocumentamount;
    @XmlElement(name = "AUTHORITY_AMOUNT", required = true)
    protected String authorityamount;
    @XmlElement(name = "UNROUNDED_AUTHORITY_AMOUNT", required = true)
    protected String unroundedauthorityamount;
}

