//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.30 at 10:27:01 AM PST
//

package com.nike.mptaxmanager.model.onesource.response;

import com.nike.mptaxmanager.model.ErrorResponse;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tax.wsdl
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConvertedCurrencyAmountType }
     *
     */
    public ConvertedCurrencyAmountType createConvertedCurrencyAmountType() {
        return new ConvertedCurrencyAmountType();
    }

    /**
     * Create an instance of {@link Outdata }
     *
     */
    public Outdata createOutdataType() {
        return new Outdata();
    }

    /**
     * Create an instance of {@link OutdataTaxSummaryType }
     *
     */
    public OutdataTaxSummaryType createOutdataTaxSummaryType() {
        return new OutdataTaxSummaryType();
    }

    /**
     * Create an instance of {@link OutdataErrorType }
     *
     */
    public OutdataErrorType createOutdataErrorType() {
        return new OutdataErrorType();
    }

    /**
     * Create an instance of {@link QuantitiesType }
     *
     */
    public QuantitiesType createQuantitiesType() {
        return new QuantitiesType();
    }

    /**
     * Create an instance of {@link OutdataTaxType }
     *
     */
    public OutdataTaxType createOutdataTaxType() {
        return new OutdataTaxType();
    }

    /**
     * Create an instance of {@link OutdataInvoiceType }
     *
     */
    public OutdataInvoiceType createOutdataInvoiceType() {
        return new OutdataInvoiceType();
    }

    /**
     * Create an instance of {@link CurrencyConversionType }
     *
     */
    public CurrencyConversionType createCurrencyConversionType() {
        return new CurrencyConversionType();
    }

    /**
     * Create an instance of {@link OutdataLineType }
     *
     */
    public OutdataLineType createOutdataLineType() {
        return new OutdataLineType();
    }

    /**
     * Create an instance of {@link QuantityType }
     *
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link OutdataRequestStatusType }
     *
     */
    public OutdataRequestStatusType createOutdataRequestStatusType() {
        return new OutdataRequestStatusType();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     *
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }
}

