//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 10:27:01 AM PST 
//


package com.nike.mptaxmanager.model.onesource.response;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class OutdataTaxSummaryType {

    @XmlElement(name = "TAXABLE_BASIS")
    protected String taxablebasis;
    @XmlElement(name = "NON_TAXABLE_BASIS", required = true)
    protected String nontaxablebasis;
    @XmlElement(name = "EXEMPT_AMOUNT", required = true)
    protected String exemptamount;
    @XmlElement(name = "TAX_RATE", required = true)
    protected String taxrate;
    @XmlElement(name = "EFFECTIVE_TAX_RATE")
    protected String effectivetaxrate;
}

