//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 10:27:01 AM PST 
//


package com.nike.mptaxmanager.model.onesource.request;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class CommonAddressType {

    @XmlElement(name = "COUNTRY")
    protected String country;
    @XmlElement(name = "PROVINCE")
    protected String province;
    @XmlElement(name = "STATE")
    protected String state;
    @XmlElement(name = "COUNTY")
    protected String county;
    @XmlElement(name = "CITY")
    protected String city;
    @XmlElement(name = "DISTRICT")
    protected String district;
    @XmlElement(name = "POSTCODE")
    protected String postcode;
    @XmlElement(name = "GEOCODE")
    protected String geocode;
}

