//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 10:27:01 AM PST 
//


package com.nike.mptaxmanager.model.onesource.request;

import lombok.Data;

import javax.xml.bind.annotation.*;
import java.util.List;

@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "INDATA")
public class Indata {

    @XmlElement(name = "USERNAME")
    protected String username;
    @XmlElement(name = "PASSWORD")
    protected String password;
    @XmlElement(name = "INVOICE")
    protected List<IndataInvoiceType> invoice;
    @XmlAttribute(name = "ORDER_NO")
    protected String orderno;
    @XmlAttribute(name = "ENTERPRISE_CODE")
    protected String enterprisecode;
    @XmlAttribute(name = "xmlns")
    protected String xmlns;
}

