//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 10:27:01 AM PST 
//


package com.nike.mptaxmanager.model.onesource.request;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tax.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Indata }
     * 
     */
    public Indata createIndataType() {
        return new Indata();
    }

    /**
     * Create an instance of {@link UserElementType }
     * 
     */
    public UserElementType createUserElementType() {
        return new UserElementType();
    }

    /**
     * Create an instance of {@link LocationNameType }
     * 
     */
    public LocationNameType createLocationNameType() {
        return new LocationNameType();
    }

    /**
     * Create an instance of {@link IndataLineType }
     * 
     */
    public IndataLineType createIndataLineType() {
        return new IndataLineType();
    }

    /**
     * Create an instance of {@link QuantitiesType }
     * 
     */
    public QuantitiesType createQuantitiesType() {
        return new QuantitiesType();
    }

    /**
     * Create an instance of {@link CommonAddressType }
     * 
     */
    public CommonAddressType createCommonAddressType() {
        return new CommonAddressType();
    }

    /**
     * Create an instance of {@link IndataInvoiceType }
     * 
     */
    public IndataInvoiceType createIndataInvoiceType() {
        return new IndataInvoiceType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

}

